version: "3"
services:
  
    # Launch a MySQL instance that will be available on port 3306.
    # It uses the volume named "db". It will create a default database named "dev" as well as a default
    # user named "dev" with password "dev".
    
    mysql:
        image: mariadb:10.4
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev
    
<<<<<<< HEAD
    # Launch a phpmyadmin available on http://localhost:8001 . It is already connected to the MySQL instance.
=======
    # Launch a phpmyadmin available on http://localhost:8001.
    # It is already connected to the MySQL instance.
>>>>>>> origin/dev_commun
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
          - mysql
        ports:
            - "8001:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: dev
            PMA_PASSWORD: dev
            
<<<<<<< HEAD
    # Launch a mailcatcher. Its admin is available on http://localhost:8002 . It's only useful if some program
    # is configured to send mails to it using the port 1025.
=======
    # Launch a mailcatcher. Its admin is available on http://localhost:8002.
    # It's only useful if some program is configured to send mails to it using the port 1025.
>>>>>>> origin/dev_commun
            
    mailcatcher:
        image: tophfr/mailcatcher
        ports:
            - "1025:25"
            - "8002:80"

volumes:
<<<<<<< HEAD
    db:
=======
    db:
>>>>>>> origin/dev_commun
