version: "3"
services:

    # Launch a MySQL instance that will be available on port 3306.
    # It uses the volume named "db". It will create a default database named "dev" as well as a default
    # user named "dev" with password "dev".

    mysql:
        image: mariadb:10.4
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev
            MYSQL_USER: dev
            MYSQL_PASSWORD: dev

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
          - mysql
        ports:
            - "8001:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: dev
            PMA_PASSWORD: dev

    mailcatcher:
        image: tophfr/mailcatcher
        ports:
            - "1025:25"
            - "8002:80"

volumes:
    db:
